@extends('layouts.template')
@section('content')
<table class="table table-bordered table-striped">
    <thead>
        <tr>
            <th>No.</th>
            <th>Nama</th>
            <th>Kelas</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>1.</td>
            <td>Faiz</td>
            <td>B</td>
        </tr>
        <tr>
            <td>2.</td>
            <td>Indra</td>
            <td>B</td>
        </tr>
        <tr>
            <td>3.</td>
            <td>Najib</td>
            <td>B</td>
        </tr>
        <tr>
            <td>4.</td>
            <td>Joseph</td>
            <td>B</td>
        </tr>
    </tbody>
</table>
@endsection